subset functions for RDMs objects
rsagroup/rsatoolbox pull request #45
Opened 2019-12-09 23:09 UTC by HeikoSchuett

Implementing the subset function equivalents for RDMs as for dataset

2019-12-13 09:38 UTC, iancharest requested changes
Hi Heiko,
1)
in `def get_vectors(self):` 
the docstring is a bit confusing: 
```python
    """ Returns RDMs as np.ndarray with each RDM as a vector
        Returns:
            RDMs as with one vector as one RDM
    """
```
same for get_matrices
```python
        """ Returns RDMs as np.ndarray with each RDM as a matrix
        Returns:
            RDMs as with one matrix as one RDM
        """
```
"RDMs as with one matrix as one RDM" what does this mean? 

otherwise this looks good.

2019-12-13 15:38 UTC, HeikoSchuett commented
Hi, I now merged the master back in and fixed the help messages. Thank you for having a look!

2019-12-13 15:42 UTC, iancharest approved these changes
great!

2020-01-13 22:31 UTC, eberlot approved these changes

2020-01-13 22:37 UTC, merged